export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

//TYPES DE PEDIDO
export const MOSTRAR_SELECCIONADO = 'MOSTRAR_SELECCIONADO';
export const BUSCAR_PEDIDO = 'BUSCAR_PEDIDO';
export const RESET_BUSCAR = 'RESET_BUSCAR';
export const OBTENER_PEDIDOS = 'OBTENER_PEDIDOS';
export const EDITAR_PEDIDO = 'EDITAR_PEDIDO';
export const AGREGAR_PEDIDO = 'AGREGAR_PEDIDO';
export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO';
export const ERROR_PEDIDOS = 'ERROR_PEDIDOS';

//TYPES DE USUARIO
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const ERROR = 'ERROR';